<?php

/**
 * @file
 * Contains protect_before_launch.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function protect_before_launch_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the protect_before_launch module.
    case 'help.page.protect_before_launch':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Protect your site before launch with HTTP basic authentication') . '</p>';
      return $output;

    default:
  }
}
